version: '3'

services:
  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - mysql
  adminer:
      image: adminer
      ports:
        - 8080:8080
      networks:
        - mysql

networks:
  mysql:
    driver: bridge
